### ISSUE TITLE
可不可加上Seata玩一把呢？

### ISSUE THREAD

**Issue by gnehcgnaw** [funtl/MyShopPlus#1]
期待的架构升级，我也在研究这些东西，都是因为听了你的课，哈哈。

**Comment by topsale** [comment]
> 期待的架构升级，我也在研究这些东西，都是因为听了你的课，哈哈。

当前架构中的数据库采用的时 TiDB 已经解决分布式事务问题了呢

**Comment by gnehcgnaw** [comment]
哦哦哦，满心期待。
